StartupEvents.registry("item", event => {
	event.create('difficulty_changer')
		.displayName("§6难度切换器")
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip1'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip2'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip3'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip4'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip5'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip6'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip7'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip8'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip9'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip10'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip11'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip12'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip13'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip14'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip15'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip16'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip17'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip18'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip19'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip22'))
		.rarity("epic")

	event.create('yong_hen_star')
		.displayName("\u00A7b永恒之星")
		.tooltip('右键切换永恒难度')
		.tooltip('\u00A74不推荐一周目游玩')
		.rarity('Epic')
		.maxStackSize(1)
	event.create('moon_clock')
		.displayName("新月怀表")
		.tooltip(Text.translate('右键使用快进到新月(一次性)'))

})
